name: Manual Trigger Workflow

on:
  workflow_dispatch:
  

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Output Text
        run: echo "Message from user"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


